name: Test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - run: bundle install
      - run: pip install -r test-requirements.txt
      - run: gitshelf install
      - run: kitchen test
